
language: node_js
node_js:
  - "13.1.0"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm install -g angular-cli
    - npm install
    

script:
  - npm run test