language: node_js
node_js:
- 13.1.0
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: latest
  sonarcloud:
    organization: "sytw2019"
    token:
       secure: "ErFDBZfOMiwRkRP9DhUJQpdorDJCu2EfuKYap4VgWT8WWVHyZ29xySm6hDSUqDArGUxKzOc19HUSANlySoytErVvWXMsm5bSZu7ys3vxvNwu7LO5BfrwD6mZxbHUibjXzVAexk9uMg0XIJNc7zAcp/ecIG7edLGABkNCT7wHRCwT05W2udkvlwcDJjdEoRSMAit2lLVuTrgJ1KU2IBb1k9JdpRFpqBCjBPitYM4VKos3r20MLtAW10qUkKetuROL5COV6UC4VV35SvsYKFcLQMViN092WMvMh+22lNsaVHDixxovLmMnqGj9zxxaEPzkj7PX7RWolGTJKgHtIC79IcK/mss+RBS3fug9/a2tbRU8fpVipuavtrdubDHSq0KHJNiVNuLvr+JlmIJde7szBnsEDX/ykVHP3AoEvr4trtKza1/031BoNox/cVYu6bDaEv72uw3YRorHtaR0wvvcb0SJ3FwDh3XEgs8Wpt3a5DvC5y8+xpI5UehYudLCJNwAd77iuyAaBM9XvkAn1PmonzS7lFALWeeCktN01uAUlivDYrPl/ooq4ikLEsOQEfVvOZfOeUyhGzTB+OwIylC5NSzo2vQkMDh3Sv/JQL0cFUjOvotnvkRy8PqR4EJkTcwlb9Hjnn5Ufnh4t/YzIt0BPWAaZpPbq2LRc1SO6KKED4U="
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cd mean-app
  - cd frontend-ngrx
script:
  - npm install codecov -g
  - npm install
  - npm audit fix
  - cd ../../..
  - sonar-scanner -Dproject.settings=./sonar-project.properties
