language: node_js
node_js:
- 13.1.0
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
  firefox: latest
  sonarcloud:
    organization: sytw2019
    token:
      - secure: ESUTEd0QiZBLFavlz6HecPWSdxUYbjqK3r2PPXsKFV3efWYKyO5z4SkB8ir2aPtjpo0mY8JEFB9Z5F9TRr6o09qfncopH+q/9lCVbGAvNQ2uaDiVf9sVpIt4bJ+VuSmjd1J4VLGsMZ3WWA5jQ0/h4lKj7WZUqFARKIpFOLKLyU+QHUIBOxAv2H/EIlK0387ZLnXQD+LqpC/ShZ85Gi5lROPQIlK57z0mZp9S9XI3rgQwZ+uephWWPRY+IdYS8ZLYBJf84l1KjSRDLHhfzuGWGeWeDrOZLuf5tT+m6gHuJnkpK8Fndib5rz5NPkR8MJULPuR3Yx8AxtpF/0DEp0NWq7fkAlREyuMok3HuW4BaL/FtnSfLhtFQL3Wi1kjuwU+T33hbs6FPu1JVFdoqaEK4K1l5qJIaceJA/HXluGhXLM9U5Ob8KDwBIjUsIO9IvZOSiejWWEmKqMQK07YA5ZEviH3cvGGv6KGO5/Ec7F8BsXmedV3kMMTJ7jJuvgKufC02d4hAMDMR04UZmPjTgsiISqbC48YA6EkDz2OzhM/nq0SyNpGZIDBkeFaLITLvYcqiE0D40Sy0Kkf26nVb6srWujnFTZ0qMf9DjNCv4wPz4G23U+8HHxGq9xwVKvHptQiymY44lxFAbq2ficP50dn/7U2cWE+yJCFYP+vA3KmVywU=
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- cd mean-app
- cd frontend
- cd frontend-ngrx
- npm install codecov -g
- npm install

- cd ../../..
- sonar-scanner -Dsonar.login=$TOKEN_CLOUD -Dsonar.password=
env:
  global:
  - secure: h6E53YSQVcx0m7+F9V4W4QwRoO504As4dO49EQmsKnV4Mf5lXQJRzaLAPExOny2ty4gxv9QYSxtXEAOw6KqnEeHyfbawlmHKlCTStZpNw7lKVvSeehDDqxZSj2twJpNl8oEgTe92l4coXOojVPZqIl53l5hm+LRT/weB9cius+3lymUnG6Ej9P0QsXRCOi7nvJfFxEmD3dZTERr8m8sKl4TIp0xESQxk5oeIolTXkLIBQ8IYi5ML20ZGU9NK8syQmXV81ZlMBe6PSKKejocY5cwOhRBzjVmL7ltyqBNtJEGuyuIe25swsIvTLkCjRT2qjBNIL61IjvYGq/ai1ANH74pWxAbWf0i0rHdwlAcOyIRMNZ4wYkf6r0mG7ZNVcU/X+2AfkwP8xwb7/X4+xMJ3rM417rA0WgpSE+RUJS4/tARXAVO0zKOR3Z3cXq59jskECgULY8X5BjSxFJcWXW6T3hg6hbo78W78eV8DkXlk1vwQA4gz5VkMG3K1QqApySxSQLUIuOAnu9jnR1DueZ7NOFDhp17B7pchiXi1E9O0+y6j+hvKb38VeBqVk/kHI5MYZBnLKdKew459XZD2aCfJSxLo9GIKiymTN8v1GHfRqp+IoaYDiaY93kjRBQyHEdazM36pq6p135OvU0QL9x6AGeCrI3QAE+wCJmcCGwZ3ktQ=
  